run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  goimports:
    local-prefixes: github.com/kanywst/raftel
  revive:
    severity: warning
    rules:
      - name: var-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: unused-parameter
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
