{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "omega.agentName" . }}
  labels:
{{ include "omega.commonLabels" . | indent 4 }}
    app.kubernetes.io/component: agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "omega.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
{{ include "omega.commonLabels" . | indent 8 }}
        app.kubernetes.io/component: agent
    spec:
      serviceAccountName: {{ include "omega.serviceAccountName" . }}
      hostNetwork: {{ .Values.agent.hostNetwork }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: agent
          image: {{ include "omega.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            - agent
            - --socket={{ .Values.agent.socketPath }}
            - --server={{ .Values.agent.serverURL }}
            {{- range .Values.agent.uidMap }}
            - {{ printf "--map=%s" . | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          volumeMounts:
            - name: agent-sock
              mountPath: {{ dir .Values.agent.socketPath }}
      volumes:
        - name: agent-sock
          hostPath:
            path: {{ .Values.agent.hostSocketPath }}
            type: DirectoryOrCreate
{{- end }}
